### ISSUE TITLE
License for code in blog

### ISSUE THREAD

**Issue by 0xr0bert** [AtheMathmo/AtheMathmo.github.io#2]
Hi,

I was just wondering if I could use some of the code from https://athemathmo.github.io/2016/06/24/using-gmm-in-rust.html, and if so under what license?

Thanks!

**Comment by AtheMathmo** [comment]
Hi!

You can definitely use the code. Please see the [rusty-machine license](https://github.com/AtheMathmo/rusty-machine/blob/master/LICENSE.md). I am happy to discuss specifics if licensing is especially important to you but really I expect you can do whatever you want with this :)

Thank you for asking!

**Comment by 0xr0bert** [comment]
That's fantastic thank you very much!
